run:
  timeout: 3m
  tests: true
linters:
  enable:
    - govet
    - staticcheck
    - gofmt
    - gofumpt
    - revive
issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
